* sql通用语法和分类
1. sql数据库的sql语句不区分大小写，关键字建议使用大写
2. 单行注释：--或##
   多行注释：/* */
** sql分类
1. DDL：Data Definition Language
   数据定义语言，用来定义数据对象(数据库，表，字段)
2. DML：Manipulation
3. DQL：Query
4. DCL：Control
   用来创建数据库用户、控制数据库的访问权限
* DDL
** 数据库操作 
- 查询当前数据库
  select database();
- create database if not exists name;
- drop database if exists name;
** 表操作-查询
- show tables;
  查看当前数据库所有表
- desc 表名;
  查询表结构
- show create table 表名;
  建表语句
- create table 表名(字段1 类型 comment 注释) comment 注释;
  最后一个字段没有逗号
** 数据类型
1. 数值类型tinyint smallint mediumint int bigint float double decimal
   1. age tinyint unsigned
   2. score double(4,1)
      4: 整体长度 1：小数部分
2. 字符串类型
   char varchar tinyblob tinytext blob text mediumblob mediumtext longblob longtext
3. 日期类型
   date time year datetime timestamp
   1. birthday data
** 表操作-修改
- alter table 表名 add 字段名 类型(长度) comment 注释 约束;
  添加字段
- alter table 表名 modify 字段名 新数据类型(长度);
  修改数据类型
- alter table 表名 change 旧字段名 新字段名 类型(长度) comment 注释 约束;
  修改字段名和字段类型
- alter table 表名 drop 字段名;
  删除字段
- alter table 表名 rename to 新表名;
  修改表名
** 表操作-删除
- 注意：在删除表时，表中的全部数据也会被删除
- drop table if exists 表名;
  删除表
- truncate table 表名;
  删除指定表，并重新创建该表
* DML
1. insert into 表名(字段名) value(值);
   给指定字段添加数据
2. insert into 表名 value(值);
   给全部字段添加数据
3. update 表名 set  字段=值 where;
   update语句的条件可以有，也可以没有，条件如果没有，则会修改整张表的所有数据
4. delete from 表名 where ;
   delete语句的条件可以有，也可以没有，条件如果没有，则会删除整张表的所有数据
   delete语句不能删除某一个字段的值(可以使用update)
* DQL
- 编写顺序
  select from where group by having order by limit
- 执行顺序
  from where group by having select order by limit
* DCL
** 管理用户
- 创建用户
  create user '用户名'@'主机名' identified by '密码';
- 修改用户密码
  alter user '用户名'@'主机名' identified with mysql_native_password by '新密码';
- 删除用户
  drop user '用户名'@'主机名';
** 权限控制
- 常见的权限
  all,all privileges select insert update delete alter(修改表) drop(删除数据库/表/视图) create(创建数据库/表)
- 查询权限
  show grants for '用户名'@'主机名';
- 授予权限
  grant 权限列表 on 数据库名.表名 to '用户名'@'主机名';
- 撤销权限
  revoke 权限列表 on 数据库名.表名 from '用户名'@'主机名';
* 函数
** 字符串函数
1. lpad(str,n,pag)
   左填充，用字符串pad对str的左边时行填充，达到n个字符串长度
2. rpad
*** 案例
1. 由于业务需求变更，企业员工的工号，统一为5位数，目前不足5位数的全部在前面补0，比如：1号员工工号应该为00001
   update emp set workno = lpad(workno, 5, '0');
** 数值函数
1. ceill floor 向上下向取整
2. mod 模
3. rand 返回0～1内的随机数
4. round(x,y) 求参数x的四舍五入的值，保留y位小数
*** 案例
1. 通过数据库函数生成一个六位数随机验证码
   select lpad(round(rand()*1000000,0),6,'0');
** 日期函数
curdate curtime now
1. year(now())
   获取指定date的年份
2. date_add(now(), interval 70 day)
   从当前时间向后推70天
3. datediff('2021-12-01', '2021-11-01')
   两个时间相差的天数(是用前面的时间减去后面的时间)
*** 案例
1. 查询所有员工的入职天数，并根据入职天数倒序排序
   select name, datediff(curdate(), entrydate) as 'entrydays' from emp order by entrydays desc;
** 流程函数
1. if(true, 'ok', 'error') 类似三元表达式
2. ifnull('ok', 'default') 判断第一个值是否为空。如果不为空，返回该值，如果为空，返回后面默认值
3. case when thwn else end 类似switch case
   - 查询emp表的员工姓名和工作地址(北京/上海 ----> 一线城市，其它 ----> 二线城市)
     select name, (case workaddress when '北京' then '一线城市' when '上海' then '一线城市' else '二线城市' end) as '工作地址' from emp;
*** 案例
1. 统计班级各个学员的成绩，展示的规则如下：
   - >=85，展示优秀
   - >=60，展示及格
   - 否则，展示不及格
     (case when math >= 85 then '优秀' when math >= 60 then '及格' else '不及格' end) '数学'
* 约束
约束是作用于表中字段上的规则，用于限制存储在表中的数据
** 分类
非空约束(not null) 唯一约束(unique) 主键约束(primary key) 外键约束(foreign key)
- 默认约束(default)
  保存数据时，如果未指定该字段的值，则采用默认值
  status char(1) default '1' comment '状态'
- 检查约束(check) 8.0.16版本之后
  保证字段值满足某一个条件
  age int check ( age > 0 && age <= 120 ) comment '年龄'
** 外键
- 修改外键
  alter table 表名 add constraint 外键名称 foreign key(外键字段名) references 主表(主表列名);
- 删除外键
  alter table 表名 drop foreign key 外键名称;
*** 删除/更新行为
- no action/restrict
  不允许
- cascade 级联删除
  当在父表中删除/更新对应记录时，首先检查该记录是否有对应外键，如果有，则也删除/更新外键在子表中的记录。
- set null
  当在父表中删除对应记录时，首先检查该记录是否有对应外键，如果有则设置子表中该外键值为null(这就要求该外键允许取null)。
- set default
  父表有变更时，子表将外键列设置成一个默认的值(Innodb不支持)
- 使用
  alter table 表名 add constraint 外键名称 foreign key(外键字段名) references 主表(主表列名) on update cascade on delete cascade;
* 子查询
- 根据子查询结果不同，分为：
  1. 标量子查询
  2. 列子查询
  3. 行子查询
  4. 表子查询
- 根据子查询位置,分为：where之后、from之后、select之后
** 列子查询
子查询返回的结果是一列(可以是多行)，这种子查询称为列子查询
*** 常用的操作符：in、not in、any、some、all
- IN 
  在指定的集合范围之内，多选一
- NOT IN
  不在指定的集合范围之内
- ANY
  子查询返回列表中，有任意一个满足即可
- SOME
  与ANY等同，使用SOME的地方都可以使用ANY
- ALL
  子查询返回列表的所有值都必须满足
*** 案例
1. 查询“销售部”和“市场部”的所有员工信息
   1. 查询“销售部”和“市场部”的部门id
      select id from dept where name = '销售部' or name = '市场部';
   2. 根据部门id，查询员工信息
      select * from emp where dept_id in (2,4)
   3. 结果
      select * from emp where dept_id in (select id from dept where name ='销售部'or name ='市场部');
2. 查询比财务部所有人工资都高的员工信息
   1. 查询所有财务部人员工资
      select id from dept where name = '财务部';
      select salary from emp where dept_id = (select id from dept where name =‘财务部");
   2. 比财务部所有人工资都高的员工信息
      select * from emp where salary > all ( select salary from emp where dept_id = (select id from dept where name = '财务部') );
3. 查询比研发部其中任意一人工资高的员工信息
   1. 查询研发部所有人工资
      select salary from emp where dept_id =(select id from dept where name = '研发部');
   2. 比研发部其中任意一人工资高的员工信息
      Select * from emp where salary > any ( select salary from emp where dept_id = (select id from dept where name = '研发部') );
** 行子查询
子查询返回的结果是一行(可以是多列)，这种子查询称为行子查询
常用的操作符：=、<>、in、not in
*** 案例
1. 查询与“张无忌” 的薪资及直属领导相同的员工信息
   1. 查询“张无忌”的薪资及直属领导
      select salary, managerid from emp where name = '张无忌';
   2. 查询与“张无忌” 的薪资及直属领导相同的员工信息
      1. select * from emp where salary = 12500 and managerid = 1;
      2. 另一种写法：select * from emp where (salary,managerid) = (12500,1);
      3. 综上：select * from emp where (salary,managerid) = (select salary, managerid from emp where name = '张无忌');
** 表子查询
常用的操作符：in
*** 案例
1. 查询与“鹿杖客”，“宋远桥”的职位和薪资相同的员工信息
   1. 查询“鹿杖客”，“宋远桥”的职位和薪资
      select job, salary from emp where name = '鹿杖客' or name = ‘宋远桥';
   2. 查询与“鹿杖客”，“宋远桥”的职位和薪资相同的员工信息
      select * from emp where (job,salary) in ( select job, salary from emp where name = '鹿杖客' or name = '宋远桥');
2. 查询入职日期是“2006-01-01”之后的员工倍息，及其部门倍息
   1. 入职日期是“2006-01-01”之后的员工倍息
      select * from emp where entrydate > '2006-01-01';
   2. 查询这部分员工，对应的部门信息;
      select e.*, d.* from (select * from emp where entrydate > '2006-01-01') e left join dept d on e.dept_id = d.id ;
* 多表查询练习
1. 查询低于本部门平均薪资的员工信息
   1. 查询指定部门平均薪资 1
      select avg(e1.salary) from emp e1 where e1.dept_id = 1;
   2. select * from emp e2 where e2.salary <  ( select avg(e1.salary) from emp el where e1.dept_id = e2.dept_id );
      子查询+自连接
2. 查询所有部门信息，并统计部门的员工人数
   select d.id, d.name, ( select count(*) from emp e where e.dept_id = d.id )'人数' from dept d;
3. 查询所有学生的选课情况，展示出学生名称，学号，课程名称
   select s.name , s.no , c.name from student s , student_course sc , course c where s.id = sc.studentid and sc.courseid = c.id;
* 事务
** 事务四大特性
1. 原子性(Atomicity):事务是不可分割的最小操作单元，要么全部成功，要么全部失败。
2. 一致性(Consistency):事务完成时，必须使所有的数据都保持一致状态。
3. 隔离性(Isolation):数据库系统提供的隔离机制，保证事务在不受外部并发操作影响的独立环境下运行。
4. 持久性(Durability):事务一旦提交或回滚，它对数据库中的数据的改变就是永久的。
** 并发事务问题
- 脏读
  一个事务读到另外一个事务还没有提交的数据。
- 不可重复读
  一个事务先后读取同一条记录，但两次读取的数据不同，称之为不可重复读。
- 幻读
  一个事务按照条件查询数据时，没有对应的数据行，但是在插入数据时，又发现这行数据已经存在，好像出现了”幻影”。
** 4种隔离级别
1. Read uncommitted
   性能高
2. Read committed
   解决脏读
3. Repeatable Read(默认)
   解决不可重复读
4. Serializable
   解决幻读
** 命令
- 查看事务的隔离级别
  select @@transaction_isolation;
- set session transaction isolation level read uncommitted
  修改隔离级别
* 索引
索引是一种有序的数据结构，这种数据结构是用来高效获取数据的
- 索引的缺点
  - 占用磁盘空间
  - 降低了更新表的速度
** 索引结构
- B-Tree
  以一颗最大度数(max-degree)为5阶的b-tree为例(每个节点最多存储4个key，5个指针):
  最大度数为5：一个结点下面最多有5个字结点
- B+Tree
  - 所有元素出现在叶子节点
  - 叶子节点形成一个单向链表
** 索引分类
主键索引，唯一索引，常规索引，全文索引
在InnoDB存储引擎当中，根据索引的存储形式，又可以分为以下两种：
1. 聚焦索引
   将数据存储与索引放到了一块，索引结构的叶子节点保存了行数据
2. 二级索引
   将数据与索引分开存储，索引结构的叶子节点关联的是对应的主键
*** 聚焦索引选取规则
1. 如果存在主键，主键索引就是聚焦索引
2. 如果不存在主键，将使用第一个唯一索引作为聚集索引
3. 如果表没有主键没有主键，或没有合适的唯一索引，则InnoDB会自动生成一个rowid作为隐藏的聚焦索引
*** 索引语法
- 创建索引
  create [unique|fulltext] index_name on table_name(index_col_name);
- 查看索引
  show index from table_name;
- 删除索引
  drop index index_name on table_name;
** 性能分析
- 查看当前数据库的执行频次
  show global status like ‘Com_______’
- 慢查询日志
  慢查询日志记录了所有执行时间超过指定参数(long_query_time，单位:秒，默认10秒)的所有SQL语句的日志。
  - MySQL的慢查询日志默认没有开启，需要在MySQL的配置文件(/etc/my.cnf)中配置如下信息:
    slow_query_log=1
    long_query_time=2
*** profile详情
  show profiles能够在做SQL优化时帮助我们了解时间都耗费到哪里去了。
  - 通过have_profiling参数，能够看到当前MySQL是否支持profile操作:
    select @@have_profiling;
  - 默认profiling是关闭的，可以通过set语句在session\global级别开启profiling
    set profiling=1;
  - 查看每一条sql的耗时基本情况
    show profiles;
  - 查看指定query_id的sql语句各个阶段的耗时情况
    show profile for query_id;
  - 查看指定query_id的sql语句cpu的使用情况
    show profile cpu for query_id;
*** explain执行计划
  EXPLAIN或者 DESC命令获取MySQL如何执行 SELECT 语句的信息，包括在SELECT语句执行过程中表如何连接和连接的顺序。
  - 语法:
    直接在select语句之前加上关键字explain/desc
    EXPLAIN SELECT 字段列表 FROM 表名 WHERE 条件;
  - explain执行计划各字段的含义
    - id
      select查询的序列号，表示查询 =执行select子句= 或者是操作表的顺序
      id相同，执行顺序从上到下; id不同，值越大，越先执行
    - select_type
      表示SELECT的类型，常见的取值有SIMPLE(简单表，即不使用表连接或者子查询)、PRIMARY(主查询，即外层的查询)、UNION(UNION中的第二个或者后面的查询语句)、SUBQUERY(SELECT/WHERE之后包含了子查询)等
    - type
      表示连接类型，性能由好到差的连接类型为NULL、system、const、eq_ref、ref、range、index、all。
      - null 不访问任何表
      - system 访问系统表
      - const 根据主键或唯一索引访问
      - ref 非唯一性索引
    - possible_key
      显示可能用到的索引
    - key
      实际用到的索引，如果为null，则没有使用索引
    - key_len
      表示索引中使用的字节数，该值为索引字段最大可能长度，并非实际使用长度，在不损失精确性的前提下，长度越短越好。
    - row
      MySQL认为必须要执行查询的行数，在innodb引擎的表中，是一个估计值，可能并不总是准确的。
    - filtered
      表示返回结果的行数占需读取行数的百分比，filtered的值越大越好。
** 最左前缀法则
查询必须包含索引当中最左边的列，如果最左边的列不存在，那么索引将会全部失效，如果查询的时候跳过了某列，索引将会部分失效
*** 范围查询
联合索引中，出现范围查询，范围查询右侧的列索引失效
规避方案，在业务允许的情况下，使用>=
** 索引失效情况
1. 不要在索引上进行运算操作，索引将失效
   expain select * from tb_user where substring(phone,10,2) = '15';
2. 字符串类型字段使用时，不加引号，索引将失效
3. 模糊查询
   如果仅仅是尾部模糊匹配，索引不会失效。如果是头部模糊匹配，索引失效
4. or两边的列都必须有索引
5. 如果mysql评估使用索引比全表更慢，则不使用索引
   1. 如果>=返回的数据很多，不会走索引
   2. 关于 is null 和 is not null 谁会走索引
      不是固定的，主要是看查到的数据多少，如果查到数据少就走索引，查到数据多就走全表扫描
** sql提示
SQL提示，是优化数据库的一个重要手段，简单来说，就是在SQL语句中加入一些人为的提示来达到优化操作的目的。
- use index
  建议mysql用指定的索引，至于用不用由mysql决定
  explain select*from tb_user use index(idx_user_pro) where profession ='软件工程';
- ignore index
- force index
** 覆盖索引
在where条件满足联合索引的最左前缀法则的情况下，如果select查询的所有字段在联合索引中存在，就不需要回表
** 前缀索引
当字段类型为字符串(varchar，text等)时，有时候需要索引很长的字符串，这会让索引变得很大，查询时，浪费大量的磁盘IO，影响查询效率。此时可以只将字符串的一部分前缀，建立索引，这样可以大大节约索引空间，从而提高索引效率。
* sql优化
** 插入数据
- 批量插入(500-1000)
- 手动提交事务
- 主键顺序插入
- 大批量插入数据
  使用load指令
  #+begin_src sh
    #客户端连接服务端时，加上参数 --local-infile
    mysql --local-infile -uroot -p
    #设置全局参数local_infile为人，开启从本地加载文件导入数据的开关
    set global local_infile=1;
    #执行load指令将准备好的数据，加载到表结构中
    load data local infile 'root/sql1.log' into table ‘tb_user fields terminated by ',' lines terminated by '\n';
  #+end_src
** 主键优化
- 满足业务需求的情况下，尽量降低主键的长度
- 插入数据时，尽量选择顺序插入，选择使用AUTO_INCRMENT自增主键
- 尽量不要使用UUID做主键或者其它自然主键，如身份证号
- 业务操作时，避免对主键的修改
** order by优化
